@baseUrl = http://localhost:8080/api/logs
@logId = REPLACE_AFTER_CREATE
@token = REPLACE_AFTER_LOGIN

### Get log by id
GET {{baseUrl}}/{{logId}}
Authorization: Bearer {{token}}
Accept: application/json
