@baseUrl = http://localhost:8080/api/templates
@templateId = REPLACE_AFTER_CREATE
@userId = 019d059e-d220-71db-8a1a-ec7569490000

### Delete workout template
DELETE {{baseUrl}}/{{templateId}}?userId={{userId}}
