@baseUrl = http://localhost:8080/api/templates
@token = REPLACE_AFTER_LOGIN

### Create workout template
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Push + Cardio",
  "exercises": [
    {
      "exerciseId": "019d059e-d220-71db-8a1a-ec7569490001",
      "order": 0,
      "sets": [
        { "type": "Strength", "order": 0, "reps": 8 },
        { "type": "Strength", "order": 1, "reps": 8 },
        { "type": "Strength", "order": 2, "reps": 6 }
      ]
    },
    {
      "exerciseId": "019d059e-d220-71db-8a1a-ec7569490061",
      "order": 1,
      "sets": [
        { "type": "Plyometric", "order": 0, "reps": 10 },
        { "type": "Plyometric", "order": 1, "reps": 10 }
      ]
    },
    {
      "exerciseId": "019d059e-d220-71db-8a1a-ec7569490051",
      "order": 2,
      "sets": [
        { "type": "Cardio", "order": 0, "duration": "00:20:00", "distance": 3.5, "distanceUnit": "Km" }
      ]
    }
  ]
}
