@baseUrl = http://localhost:8080/api/templates
@templateId = REPLACE_AFTER_CREATE
@token = REPLACE_AFTER_LOGIN

### Delete workout template
DELETE {{baseUrl}}/{{templateId}}
Authorization: Bearer {{token}}
