@baseUrl = http://localhost:8080/api/users
@token = REPLACE_WITH_JWT
@userId = REPLACE_WITH_USER_GUID

### Change password
POST {{baseUrl}}/{{userId}}/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "supersecret123",
  "newPassword": "evenmoresecret456"
}
