@baseUrl = http://localhost:8080/api/users

### Register user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "rune@example.com",
  "username": "rune",
  "password": "supersecret123",
  "weight": 72.5,
  "height": 180,
  "activeDays": 4
}
