<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviours\" />
    <Folder Include="Common\Mappings\" />
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bloom.Domain\Bloom.Domain.csproj" />
  </ItemGroup>

</Project>
