services:
  bloom-api:
    build: .
    ports:
      - 8080:5000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bloom-network

  postgres:
    image: postgres:16
    container_name: bloom-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloom_user -d bloom_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - bloom-network

volumes:
  postgres_data:

networks:
  bloom-network:
    driver: bridge
