// <auto-generated />
using System;
using Bloom.Infrastructure.Persistence.EntityFramework.Configuration.Vendors;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bloom.Infrastructure.Persistence.EntityFramework.Migrations.PostgreSQL
{
    [DbContext(typeof(PostgresDomainDbContext))]
    [Migration("20260508140512_AddUserBodyMetrics")]
    partial class AddUserBodyMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bloom.Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("Bloom.Domain.LoggedWorkouts.LoggedWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("LoggedWorkouts", (string)null);
                });

            modelBuilder.Entity("Bloom.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveDays")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Bloom.Domain.WorkoutTemplates.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates", (string)null);
                });

            modelBuilder.Entity("Bloom.Domain.Exercises.Exercise", b =>
                {
                    b.OwnsMany("Bloom.Domain.Exercises.ValueObjects.TargetMuscle", "TargetMuscles", b1 =>
                        {
                            b1.Property<Guid>("ExerciseId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Value")
                                .IsRequired();

                            b1.HasKey("ExerciseId", "__synthesizedOrdinal");

                            b1.ToTable("Exercises");

                            b1
                                .ToJson("TargetMuscles")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseId");
                        });

                    b.Navigation("TargetMuscles");
                });

            modelBuilder.Entity("Bloom.Domain.LoggedWorkouts.LoggedWorkout", b =>
                {
                    b.OwnsMany("Bloom.Domain.LoggedWorkouts.LoggedExercise", "LoggedExercises", b1 =>
                        {
                            b1.Property<Guid>("LoggedWorkoutId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("ExerciseId");

                            b1.Property<Guid>("Id");

                            b1.Property<int>("Order");

                            b1.HasKey("LoggedWorkoutId", "__synthesizedOrdinal");

                            b1.ToTable("LoggedWorkouts");

                            b1
                                .ToJson("LoggedExercises")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LoggedWorkoutId");

                            b1.OwnsMany("Bloom.Domain.LoggedWorkouts.LoggedSet", "Sets", b2 =>
                                {
                                    b2.Property<Guid>("LoggedExerciseLoggedWorkoutId");

                                    b2.Property<int>("LoggedExercise__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<TimeSpan?>("Duration");

                                    b2.Property<Guid>("Id");

                                    b2.Property<int>("Order");

                                    b2.Property<int?>("Reps");

                                    b2.Property<int?>("Rir");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("LoggedExerciseLoggedWorkoutId", "LoggedExercise__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("LoggedWorkouts");

                                    b2.WithOwner()
                                        .HasForeignKey("LoggedExerciseLoggedWorkoutId", "LoggedExercise__synthesizedOrdinal");

                                    b2.OwnsOne("Bloom.Domain.LoggedWorkouts.ValueObjects.Distance", "Distance", b3 =>
                                        {
                                            b3.Property<Guid>("LoggedSetLoggedExerciseLoggedWorkoutId");

                                            b3.Property<int>("LoggedSetLoggedExercise__synthesizedOrdinal");

                                            b3.Property<int>("LoggedSet__synthesizedOrdinal");

                                            b3.Property<string>("Unit")
                                                .IsRequired();

                                            b3.Property<decimal>("Value");

                                            b3.HasKey("LoggedSetLoggedExerciseLoggedWorkoutId", "LoggedSetLoggedExercise__synthesizedOrdinal", "LoggedSet__synthesizedOrdinal");

                                            b3.ToTable("LoggedWorkouts");

                                            b3.WithOwner()
                                                .HasForeignKey("LoggedSetLoggedExerciseLoggedWorkoutId", "LoggedSetLoggedExercise__synthesizedOrdinal", "LoggedSet__synthesizedOrdinal");
                                        });

                                    b2.OwnsOne("Bloom.Domain.LoggedWorkouts.ValueObjects.Weight", "Weight", b3 =>
                                        {
                                            b3.Property<Guid>("LoggedSetLoggedExerciseLoggedWorkoutId");

                                            b3.Property<int>("LoggedSetLoggedExercise__synthesizedOrdinal");

                                            b3.Property<int>("LoggedSet__synthesizedOrdinal");

                                            b3.Property<string>("Unit")
                                                .IsRequired();

                                            b3.Property<decimal>("Value");

                                            b3.HasKey("LoggedSetLoggedExerciseLoggedWorkoutId", "LoggedSetLoggedExercise__synthesizedOrdinal", "LoggedSet__synthesizedOrdinal");

                                            b3.ToTable("LoggedWorkouts");

                                            b3.WithOwner()
                                                .HasForeignKey("LoggedSetLoggedExerciseLoggedWorkoutId", "LoggedSetLoggedExercise__synthesizedOrdinal", "LoggedSet__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Distance");

                                    b2.Navigation("Weight");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("LoggedExercises");
                });

            modelBuilder.Entity("Bloom.Domain.WorkoutTemplates.WorkoutTemplate", b =>
                {
                    b.OwnsMany("Bloom.Domain.WorkoutTemplates.TemplateExercise", "TemplateExercises", b1 =>
                        {
                            b1.Property<Guid>("WorkoutTemplateId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("ExerciseId");

                            b1.Property<Guid>("Id");

                            b1.Property<int>("Order");

                            b1.HasKey("WorkoutTemplateId", "__synthesizedOrdinal");

                            b1.ToTable("WorkoutTemplates");

                            b1
                                .ToJson("TemplateExercises")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkoutTemplateId");

                            b1.OwnsMany("Bloom.Domain.WorkoutTemplates.PlannedSet", "Sets", b2 =>
                                {
                                    b2.Property<Guid>("TemplateExerciseWorkoutTemplateId");

                                    b2.Property<int>("TemplateExercise__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<TimeSpan?>("Duration");

                                    b2.Property<Guid>("Id");

                                    b2.Property<int>("Order");

                                    b2.Property<int?>("Reps");

                                    b2.Property<int>("Type");

                                    b2.HasKey("TemplateExerciseWorkoutTemplateId", "TemplateExercise__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("WorkoutTemplates");

                                    b2.WithOwner()
                                        .HasForeignKey("TemplateExerciseWorkoutTemplateId", "TemplateExercise__synthesizedOrdinal");

                                    b2.OwnsOne("Bloom.Domain.WorkoutTemplates.ValueObjects.PlannedDistance", "Distance", b3 =>
                                        {
                                            b3.Property<Guid>("PlannedSetTemplateExerciseWorkoutTemplateId");

                                            b3.Property<int>("PlannedSetTemplateExercise__synthesizedOrdinal");

                                            b3.Property<int>("PlannedSet__synthesizedOrdinal");

                                            b3.Property<int>("Unit");

                                            b3.Property<decimal>("Value");

                                            b3.HasKey("PlannedSetTemplateExerciseWorkoutTemplateId", "PlannedSetTemplateExercise__synthesizedOrdinal", "PlannedSet__synthesizedOrdinal");

                                            b3.ToTable("WorkoutTemplates");

                                            b3.WithOwner()
                                                .HasForeignKey("PlannedSetTemplateExerciseWorkoutTemplateId", "PlannedSetTemplateExercise__synthesizedOrdinal", "PlannedSet__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Distance");
                                });

                            b1.Navigation("Sets");
                        });

                    b.Navigation("TemplateExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
